[platformio]
src_dir = firmware/m5stickc_plus2_sensor_link/src

[env:m5stick-c-plus2]
platform = platformio/espressif32@7.0.1
board = m5stick-c
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5StickCPlus2@^1.0.2
lib_ignore =
    DFRobot_GP8XXX
build_flags =
    -DCORE_DEBUG_LEVEL=1
